-- MySQL Script generated by MySQL Workbench
-- Sun Feb 23 17:07:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjectDB2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjectDB2` ;

-- -----------------------------------------------------
-- Schema ProjectDB2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectDB2` DEFAULT CHARACTER SET utf8 ;
USE `ProjectDB2` ;

-- -----------------------------------------------------
-- Table `ProjectDB2`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Patient` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Patient` (
  `patient_ID` INT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `birth` DATE NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `county` VARCHAR(45) NULL,
  `post_code` VARCHAR(10) NULL,
  `email` VARCHAR(45) NOT NULL,
  `userPass` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`HPV_Vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`HPV_Vaccination` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`HPV_Vaccination` (
  `idHPV_vaccination` INT NOT NULL AUTO_INCREMENT,
  `dose_1` DATE NULL,
  `does_2` DATE NULL,
  `does_3` DATE NULL,
  `next_dose` DATE NULL,
  `latest` TINYINT NULL,
  PRIMARY KEY (`idHPV_vaccination`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`HEP_AB_Vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`HEP_AB_Vaccination` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`HEP_AB_Vaccination` (
  `idHEP B Vaccination` INT NULL AUTO_INCREMENT,
  `dose_1` DATE NULL,
  `dose_2` DATE NULL,
  `dose_3` DATE NULL,
  `next_dose` DATE NULL,
  `latest` TINYINT NULL,
  PRIMARY KEY (`idHEP B Vaccination`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`STI_Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`STI_Test` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`STI_Test` (
  `idSTI_Test` INT NOT NULL AUTO_INCREMENT,
  `date_tested` VARCHAR(45) NULL,
  `date_completed` VARCHAR(45) NULL,
  `complete` VARCHAR(45) NULL,
  `notes` VARCHAR(45) NULL,
  `last_test` VARCHAR(45) NULL,
  PRIMARY KEY (`idSTI_Test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`Patient_rersources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Patient_rersources` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Patient_rersources` (
  `idPatient_help` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `sub_category` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatient_help`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`STI_email_reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`STI_email_reminder` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`STI_email_reminder` (
  `severity` VARCHAR(45) NULL,
  `date_created` VARCHAR(45) NULL,
  `completed` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`Interview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Interview` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Interview` (
  `interview_id` INT NOT NULL AUTO_INCREMENT,
  `happy` VARCHAR(45) NULL,
  `out` VARCHAR(45) NULL,
  `talk_about_it` VARCHAR(45) NULL,
  `Interviewcol` VARCHAR(45) NULL,
  `date_completed` VARCHAR(45) NULL,
  `latest` VARCHAR(45) NULL,
  PRIMARY KEY (`interview_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`Happiness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Happiness` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Happiness` (
  `you_happy` TINYINT NULL,
  `why` VARCHAR(150) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`Out`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Out` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Out` (
  `out_friends` TINYINT NULL,
  `out_family` TINYINT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`Alcohol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Alcohol` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Alcohol` (
  `cut_down` TINYINT NULL,
  `criticised_drinking` TINYINT NULL,
  `guilty` TINYINT NULL,
  `drink_morning` TINYINT NULL,
  `club_drugs` TINYINT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`Fitness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`Fitness` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`Fitness` (
  `excercise_regularly` TINYINT NULL,
  `smoke` TINYINT NULL,
  `help_stop_smoking` TINYINT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`HPV_Reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`HPV_Reminder` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`HPV_Reminder` (
  `idHPV_Reminder` INT NULL AUTO_INCREMENT,
  `severity` INT NULL,
  `date_created` DATE NULL,
  `completed` TINYINT NULL,
  PRIMARY KEY (`idHPV_Reminder`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB2`.`HEP_Reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB2`.`HEP_Reminder` ;

CREATE TABLE IF NOT EXISTS `ProjectDB2`.`HEP_Reminder` (
  `idHEP_Reminder` INT NULL AUTO_INCREMENT,
  `severity` INT NULL,
  `date_created` DATE NULL,
  `completed` TINYINT NULL,
  PRIMARY KEY (`idHEP_Reminder`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
