-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 09:55:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `age` INT NULL,
  `house_num` INT NULL,
  `street_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `county` VARCHAR(45) NULL,
  `post_code` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`User_idUser`),
  INDEX `fk_Patient_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `idDoctor` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idDoctor`, `User_idUser`),
  INDEX `fk_Doctor_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clinic` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clinic` (
  `idClinic` INT NOT NULL,
  `clinic_name` VARCHAR(45) NULL,
  `Cliniccol` VARCHAR(45) NULL,
  PRIMARY KEY (`idClinic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HPV_vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HPV_vaccination` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HPV_vaccination` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HEP A Vacciniation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HEP A Vacciniation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HEP A Vacciniation` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HEP B Vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HEP B Vaccination` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HEP B Vaccination` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STI_Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STI_Test` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STI_Test` (
  `idSTI_Test` INT NOT NULL,
  `date_tested` VARCHAR(45) NULL,
  `date_completed` VARCHAR(45) NULL,
  `complete` VARCHAR(45) NULL,
  `notes` VARCHAR(45) NULL,
  `last_test` VARCHAR(45) NULL,
  `Patient_idPatient` INT NOT NULL,
  `Patient_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idSTI_Test`, `Patient_idPatient`, `Patient_User_idUser`),
  INDEX `fk_STI_Test_Patient1_idx` (`Patient_idPatient` ASC, `Patient_User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_STI_Test_Patient1`
    FOREIGN KEY (`Patient_User_idUser`)
    REFERENCES `mydb`.`Patient` (`User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oral_swab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oral_swab` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oral_swab` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  `Chlymidia` VARCHAR(45) NULL,
  `Gonnorea` VARCHAR(45) NULL,
  `Syphilis` VARCHAR(45) NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_Oral_swab_STI_Test`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `mydb`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rectal_swab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rectal_swab` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rectal_swab` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_Rectal_swab_STI_Test1`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `mydb`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Urine_swab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Urine_swab` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Urine_swab` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_Urine_swab_STI_Test1`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `mydb`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient_rersources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patient_rersources` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patient_rersources` (
  `idPatient_help` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `sub_category` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatient_help`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STI_email_reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STI_email_reminder` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STI_email_reminder` (
  `severity` VARCHAR(45) NULL,
  `date_created` VARCHAR(45) NULL,
  `completed` VARCHAR(45) NULL,
  `Patient_idPatient` INT NOT NULL,
  PRIMARY KEY (`Patient_idPatient`),
  INDEX `fk_STI_email_reminder_User1_idx` (`Patient_idPatient` ASC) VISIBLE,
  CONSTRAINT `fk_STI_email_reminder_User1`
    FOREIGN KEY (`Patient_idPatient`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blood_sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Blood_sample` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Blood_sample` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  `HIV` VARCHAR(45) NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_table2_STI_Test1`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `mydb`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Interview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Interview` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Interview` (
  `Patient_User_idUser` INT NOT NULL,
  `happy` VARCHAR(45) NULL,
  `out` VARCHAR(45) NULL,
  `talk_about_it` VARCHAR(45) NULL,
  `Interviewcol` VARCHAR(45) NULL,
  `date_completed` VARCHAR(45) NULL,
  `latest` VARCHAR(45) NULL,
  PRIMARY KEY (`Patient_User_idUser`),
  CONSTRAINT `fk_Interview_Patient1`
    FOREIGN KEY (`Patient_User_idUser`)
    REFERENCES `mydb`.`Patient` (`User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Happiness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Happiness` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Happiness` (
  `Interview_Patient_User_idUser` INT NOT NULL,
  `you_happy` TINYINT NULL,
  `why` VARCHAR(150) NULL,
  PRIMARY KEY (`Interview_Patient_User_idUser`),
  CONSTRAINT `fk_Happiness_Interview1`
    FOREIGN KEY (`Interview_Patient_User_idUser`)
    REFERENCES `mydb`.`Interview` (`Patient_User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Out`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Out` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Out` (
  `Interview_Patient_User_idUser` INT NOT NULL,
  `out_friends` TINYINT NULL,
  `out_family` TINYINT NULL,
  PRIMARY KEY (`Interview_Patient_User_idUser`),
  CONSTRAINT `fk_Out_Interview1`
    FOREIGN KEY (`Interview_Patient_User_idUser`)
    REFERENCES `mydb`.`Interview` (`Patient_User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alcohol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alcohol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alcohol` (
  `Interview_Patient_User_idUser` INT NOT NULL,
  `cut_down` TINYINT NULL,
  `criticised_drinking` TINYINT NULL,
  `guilty` TINYINT NULL,
  `drink_morning` TINYINT NULL,
  `club_drugs` TINYINT NULL,
  PRIMARY KEY (`Interview_Patient_User_idUser`),
  CONSTRAINT `fk_Alcohol_Interview1`
    FOREIGN KEY (`Interview_Patient_User_idUser`)
    REFERENCES `mydb`.`Interview` (`Patient_User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prep` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prep` (
  `Interview_Patient_User_idUser` INT NOT NULL,
  `on_prep` VARCHAR(45) NULL,
  `discussed` VARCHAR(45) NULL,
  PRIMARY KEY (`Interview_Patient_User_idUser`),
  CONSTRAINT `fk_Prep_Interview1`
    FOREIGN KEY (`Interview_Patient_User_idUser`)
    REFERENCES `mydb`.`Interview` (`Patient_User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fitness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fitness` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fitness` (
  `Interview_Patient_User_idUser` INT NOT NULL,
  `excercise_regularly` TINYINT NULL,
  `smoke` TINYINT NULL,
  `help_stop_smoking` TINYINT NULL,
  PRIMARY KEY (`Interview_Patient_User_idUser`),
  CONSTRAINT `fk_Fitness_Interview1`
    FOREIGN KEY (`Interview_Patient_User_idUser`)
    REFERENCES `mydb`.`Interview` (`Patient_User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
