-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 16:36:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjectDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjectDB` ;

-- -----------------------------------------------------
-- Schema ProjectDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectDB` DEFAULT CHARACTER SET utf8 ;
USE `ProjectDB` ;

-- -----------------------------------------------------
-- Table `ProjectDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`User` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`User` (
  `idUser` INT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `userPass` VARCHAR(100) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Patient` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Patient` (
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  `age` INT NULL,
  `house_num` INT NULL,
  `street_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `county` VARCHAR(45) NULL,
  `post_code` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_Patient_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ProjectDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Clinic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Clinic` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Clinic` (
  `idClinic` INT NOT NULL,
  `clinic_name` VARCHAR(45) NULL,
  `Cliniccol` VARCHAR(45) NULL,
  PRIMARY KEY (`idClinic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`HPV_vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`HPV_vaccination` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`HPV_vaccination` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`HEP A Vacciniation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`HEP A Vacciniation` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`HEP A Vacciniation` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`HEP B Vaccination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`HEP B Vaccination` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`HEP B Vaccination` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`STI_Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`STI_Test` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`STI_Test` (
  `idSTI_Test` INT NOT NULL,
  `date_tested` VARCHAR(45) NULL,
  `date_completed` VARCHAR(45) NULL,
  `complete` VARCHAR(45) NULL,
  `notes` VARCHAR(45) NULL,
  `last_test` VARCHAR(45) NULL,
  `Patient_idPatient` INT NOT NULL,
  `Patient_User_idUser` INT NOT NULL,
  PRIMARY KEY (`idSTI_Test`, `Patient_idPatient`, `Patient_User_idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Oral_swab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Oral_swab` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Oral_swab` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  `Chlymidia` VARCHAR(45) NULL,
  `Gonnorea` VARCHAR(45) NULL,
  `Syphilis` VARCHAR(45) NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_Oral_swab_STI_Test`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `ProjectDB`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Rectal_swab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Rectal_swab` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Rectal_swab` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_Rectal_swab_STI_Test1`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `ProjectDB`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Urine_swab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Urine_swab` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Urine_swab` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_Urine_swab_STI_Test1`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `ProjectDB`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`table1` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Patient_rersources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Patient_rersources` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Patient_rersources` (
  `idPatient_help` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `sub_category` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idPatient_help`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`STI_email_reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`STI_email_reminder` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`STI_email_reminder` (
  `severity` VARCHAR(45) NULL,
  `date_created` VARCHAR(45) NULL,
  `completed` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`User_idUser`),
  CONSTRAINT `fk_STI_email_reminder_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ProjectDB`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Blood_sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Blood_sample` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Blood_sample` (
  `STI_Test_idSTI_Test` INT NOT NULL,
  `HIV` VARCHAR(45) NULL,
  PRIMARY KEY (`STI_Test_idSTI_Test`),
  CONSTRAINT `fk_table2_STI_Test1`
    FOREIGN KEY (`STI_Test_idSTI_Test`)
    REFERENCES `ProjectDB`.`STI_Test` (`idSTI_Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Interview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Interview` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Interview` (
  `happy` VARCHAR(45) NULL,
  `out` VARCHAR(45) NULL,
  `talk_about_it` VARCHAR(45) NULL,
  `Interviewcol` VARCHAR(45) NULL,
  `date_completed` VARCHAR(45) NULL,
  `latest` VARCHAR(45) NULL,
  `Patient_User_idUser` INT NOT NULL,
  PRIMARY KEY (`Patient_User_idUser`),
  CONSTRAINT `fk_Interview_Patient1`
    FOREIGN KEY (`Patient_User_idUser`)
    REFERENCES `ProjectDB`.`Patient` (`User_idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Happiness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Happiness` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Happiness` (
  `you_happy` TINYINT NULL,
  `why` VARCHAR(150) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Out`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Out` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Out` (
  `out_friends` TINYINT NULL,
  `out_family` TINYINT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Alcohol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Alcohol` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Alcohol` (
  `cut_down` TINYINT NULL,
  `criticised_drinking` TINYINT NULL,
  `guilty` TINYINT NULL,
  `drink_morning` TINYINT NULL,
  `club_drugs` TINYINT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Prep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Prep` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Prep` (
  `on_prep` VARCHAR(45) NULL,
  `discussed` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectDB`.`Fitness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectDB`.`Fitness` ;

CREATE TABLE IF NOT EXISTS `ProjectDB`.`Fitness` (
  `excercise_regularly` TINYINT NULL,
  `smoke` TINYINT NULL,
  `help_stop_smoking` TINYINT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
